[tool.poetry]
name = ""
version = "0.1.0"
description = ""
authors = ["Dinara Mukhametzianova <muxametmdm@gmail.com>"]
readme = "README.md"
packages = []

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
